---
# tasks file for set_repositories
- set_fact: need_upgrade=false

- name: get codename of installation
  shell: cat /etc/lsb-release |grep CODENAME|sed -e 's/DISTRIB_CODENAME=\(.*\)/\1/g' 
  changed_when: false
  register: codename_result

- set_fact: codename={{ codename_result.stdout }}

- name: add ubuntu jp archive apt key
  apt_key:
      url: "https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg"
      state: present
  become: true
  register: result

- set_fact: need_upgrade=true
  when: result|changed

- name: add ubuntu jp ppa apt key
  apt_key:
      url: "https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg"
      state: present
  become: true
  register: result

- set_fact: need_upgrade=true
  when: result|changed

- name: download ubuntu jp team sources.list
  get_url:
      url: https://www.ubuntulinux.jp/sources.list.d/{{ codename }}.list
      dest: /etc/apt/sources.list.d/ubuntu-ja.list
      mode: 0644
  become: true
  register: result

- set_fact: need_upgrade=true
  when: result|changed

- name: change mirror server
  replace:
      dest: /etc/apt/sources.list
      regexp: ' .*://.*/ '
      replace: " {{ mirror_server }} "
  become: true
  register: result

- set_fact: need_upgrade=true
  when: result|changed

- name: add additional repos
  apt_repository:
      repo: "{{ item.repo }}"
      filename: "{{ item.filename }}"
  with_items: "{{ additional_repos }}"
  become: true
  register: result

- set_fact: need_upgrade=true
  when: result|changed

- name: apt upgrade
  apt:
      update_cache: yes
      upgrade: dist
  become: true
  when: need_upgrade == true
